name: Vulkan Triangle - Lint-Build-Test
run-name: CI by ${{ github.actor }} on ${{ github.ref_name }}.

on:
  push:
    branches:
      - develop
      - 'feat/**'
      - 'feature/**'
      - 'bugfix/**'
      - 'fix/**'
      - 'hotfix/**'
  pull_request:
    branches:
      - develop

jobs:
  linux-ci:
    name: Linux CI
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/znojse/vulkan-ci:1.4.321.1-trixie-slim-0.1.0
    steps:
      - name: Check out latest commit from branch.
        run: |
          cd /home/runner/
          git clone --depth 1 --no-checkout https://github.com/${{ github.repository }} vulkan-triangle
          cd vulkan-triangle
          git fetch origin ${{ github.ref }}
          git checkout FETCH_HEAD

      - name: Lint, build and test the project.
        run: |
          set -e
          cd /home/runner/vulkan-triangle
          conan install --profile:a ./conan-profiles/linux64-gcc --build=missing -s build_type=Debug .
          conan install --profile:a ./conan-profiles/linux64-gcc --build=missing -s build_type=Release .
          cmake --workflow --preset=vtDefaultLint
          cmake --workflow --preset=vtDefaultAll

      - run: echo "This job's status is ${{ job.status }}."
