name: Vulkan Triangle Lint-Build-Test
run-name: CI by ${{ github.actor }} on ${{ github.ref_name }}.

on:
  push:
    branches:
      - develop
      - 'feature/**'
      - 'feat/**'
  pull_request:
    branches:
      - develop

jobs:
  linux-ci:
    name: Linux CI
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/znojse/vulkan-ci:1.4.321.1-trixie-slim
      options: --user root
    steps:
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.13'

      - name: Cache pip packages.
        uses: actions/cache@v4
        with:
          path: /tmp/pip-cache
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install package dependencies.
        run: |
          set -e
          apt update && apt install -y pkg-config clang ninja-build git
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt

      - name: Check out latest commit from branch.
        uses: actions/checkout@v5
        with:
          ref: "${{ github.head_ref || github.ref_name }}"

      - name: Print checked-out branch
        run: git branch --show-current

      - name: Lint, build and test the project.
        run: |
          set -e
          conan install --profile:a ./conan-profiles/linux64-gcc --build=missing -s build_type=Debug .
          conan install --profile:a ./conan-profiles/linux64-gcc --build=missing -s build_type=Release .
          cmake --workflow --preset=vtDefaultLint
          cmake --workflow --preset=vtDefaultAll
      - run: echo "This job's status is ${{ job.status }}."

  windows-ci:
    if: false
    name: Windows CI
    runs-on: windows-latest
    steps:
      - name: Check out latest commit from branch.
        uses: actions/checkout@v5
        with:
          ref: "${{ github.event_name == 'pull_request' && github.head_ref || github.ref_name }}"

      - name: Print checked-out branch
        run: git branch --show-current

      # - name: Install Vulkan SDK
      #   run: |
      #     $version = "1.4.321.1"
      #     $url = "https://sdk.lunarg.com/sdk/download/1.4.321.1/windows/VulkanSDK-1.4.321.1-Installer.exe?Human=true"
      #     Invoke-WebRequest -Uri $url -OutFile VulkanSDKInstaller.exe
      #     Start-Process -FilePath .\VulkanSDKInstaller.exe -ArgumentList "--accept-licenses --default-answer --confirm-command install" -Wait
      #   shell: pwsh

      - name: Set up Python 3.13
        uses: actions/setup-python@v6
        with:
          python-version: '3.13'

      - name: Install package dependencies.
        run: |
          $ErrorActionPreference = 'Stop'
          pip install --upgrade pip && pip install -r requirements.txt
        shell: pwsh

      - name: Build and test the project.
        run: |
          $ErrorActionPreference = 'Stop'
          conan install --profile:a ./conan-profiles/win64-msvc --build=missing -s build_type=Debug .
          conan install --profile:a ./conan-profiles/win64-msvc --build=missing -s build_type=Release .
          cmake --workflow --preset=vtMSVCAll
        shell: pwsh
      - run: echo "This job's status is ${{ job.status }}."
