name: Vulkan Triangle Lint-Build-Test
run-name: CI by ${{ github.actor }} on ${{ github.ref_name }}.
on:
  push:
    branches:
      - develop
      - 'feature/**'
  pull_request:
    branches:
      - develop
jobs:
  Ubuntu-latest-CI:
    runs-on: ubuntu-latest
    steps:
      - name: Check out latest commit from branch.
        uses: actions/checkout@v5
      - name: Lint, build and testing the project for Ubuntu.
        run: |
          clear &&
          rm -rf build/* &&
          conan install --profile:a ./conan-profiles/linux64-gcc --build=missing -s build_type=Debug . &&
          conan install --profile:a ./conan-profiles/linux64-gcc --build=missing -s build_type=Release . &&
          cmake --workflow --preset=vtDefaultLint &&
          cmake --workflow --preset=vtDefaultAll
      - run: echo "This job's status is ${{ job.status }}."
  Windows-latest-CI:
    runs-on: windows-latest
    steps:
      - name: Check out latest commit from branch.
        uses: actions/checkout@v5
      - name: Build and testing the project for Windows.
        run: |
          clear &&
          rm -rf build/* &&
          conan install --profile:a ./conan-profiles/linux64-gcc --build=missing -s build_type=Debug . &&
          conan install --profile:a ./conan-profiles/linux64-gcc --build=missing -s build_type=Release . &&
          cmake --workflow --preset=vtDefaultLint &&
          cmake --workflow --preset=vtDefaultAll
      - run: echo "This job's status is ${{ job.status }}."