name: Vulkan Triangle Lint-Build-Test
run-name: CI by ${{ github.actor }} on ${{ github.ref_name }}.

on:
  push:
    branches:
      - develop
      - 'feature/**'
  pull_request:
    branches:
      - develop

jobs:
  Ubuntu-latest-CI:
    if: false
    name: Ubuntu-CI
    runs-on: ubuntu-latest
    steps:
      - name: Check out latest commit from branch.
        uses: actions/checkout@v5
        with:
          ref: ${{ github.head_ref || github.ref_name }}

      - name: Print checked-out branch
        run: git branch --show-current

      - name: Lint, build and test the project.
        run: |
          clear &&
          rm -rf build/* &&
          conan install --profile:a ./conan-profiles/linux64-gcc --build=missing -s build_type=Debug . &&
          conan install --profile:a ./conan-profiles/linux64-gcc --build=missing -s build_type=Release . &&
          cmake --workflow --preset=vtDefaultLint &&
          cmake --workflow --preset=vtDefaultAll
      - run: echo "This job's status is ${{ job.status }}."
  
  Windows-latest-CI:
    name: Windows-CI
    runs-on: windows-latest
    steps:
      - name: Check out latest commit from branch.
        uses: actions/checkout@v5
        with:
          ref: ${{ github.head_ref || github.ref_name }}

      - name: Print checked-out branch
        run: git branch --show-current

      # - name: Install Vulkan SDK
      #   run: |
      #     $version = "1.4.321.1"
      #     $url = "https://sdk.lunarg.com/sdk/download/1.4.321.1/windows/VulkanSDK-1.4.321.1-Installer.exe?Human=true"
      #     Invoke-WebRequest -Uri $url -OutFile VulkanSDKInstaller.exe
      #     Start-Process -FilePath .\VulkanSDKInstaller.exe -ArgumentList "--accept-licenses --default-answer --confirm-command install" -Wait
      #   shell: pwsh

      - name: Set up Python 3.13
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Create virtual environment and install dependencies.
        run: |
          python -m venv venv
          .\venv\Scripts\Activate.ps1
          python -c "import sys; print(sys.executable)"
          pip install --upgrade pip && pip install conan
          pip install --upgrade pip && pip install cmake
          pip list
        shell: pwsh

      - name: Build and test the project.
        run: |
          .\venv\Scripts\Activate.ps1
          if (Test-Path -LiteralPath build/) { Remove-Item build/* -Recurse -Force }
          conan install --profile:a ./conan-profiles/win64-msvc --build=missing -s build_type=Debug .
          conan install --profile:a ./conan-profiles/win64-msvc --build=missing -s build_type=Release .
          cmake --workflow --preset=vtMSVCAll
        shell: pwsh
      - run: echo "This job's status is ${{ job.status }}."
